config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'stories#index'

  resources :stories do 
  	get "images"
    post "favorite"
    post "unfavorite"
  end
 
  resources :segments do
  	post "up"
  	post "down"
  end
  resources :sentences
end

app/models/story.rb
class Story < ApplicationRecord
	# has_many :likes
	has_many :segments
	belongs_to :user
	acts_as_votable

	attr_accessor :sentence

	def segment_ended(last_seg_time)
		#TODO double check if this works
		Time.now - last_seg_time 
	end

	def get_last_seg
		self.segments.last
	end

	def grab_all_active_segments(last_winning_seg)

	end

	def move_segment_head
		#find all segments where time is greater than the last updated time of the last winning segment
	end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	def index
		@root_url = "https://source.unsplash.com/"
		@query = "/800x640"
		@stories = Story.paginate(:page => params[:page], :per_page => 5)
	end

	def show
		@root_url = "https://source.unsplash.com/"
		@query = "/800x640"
		@story = Story.find(params[:id])

		
		@liked = false
		# for writing a new segment
		if user_signed_in?
			@new_segment = Segment.new
			@new_sentence = Sentence.new

			
			# check for likes
			all_likes = @story.get_likes
				all_likes.each do |voters|
					if voters.voter_id == current_user.id
						@liked = true
					end
				end
			end

			#TODO refactor logic into model

			@segs = @story.segments

			# Grabs all winning segments
			@win_seg = @segs.where(winning_sentence: true)

			# Last winning segments update time
			last_seg_time = @win_seg.last.updated_at

			# Query for active segments
			@active_segs = @segs.where(["updated_at >= '%s' and winning_sentence = '%s'", last_seg_time, false])

			# Sorting active segs by vote count
			@sorted = @active_segs.sort { |a,b| b.sentence.get_vote_count <=> a.sentence.get_vote_count }

			# logic for update

			# Think about given the user access to the update time. 
			update_timer_in_sec = 1200

			#convert from UTC to PST just for display
			
			if @story.segment_ended(last_seg_time) > update_timer_in_sec
				
				#logic to make sure only stories with more than one sentence is active
				if @sorted.length > 0
					puts @story.segment_ended(last_seg_time)

					puts "it's time to udate some shit"
					winner = @sorted.shift
					winner.winning_sentence = true
					winner.save

					# Last winning segments update time
					last_seg_time = @win_seg.last.updated_at

					# Query for active segments
					@active_segs = @segs.where(["updated_at >= '%s' and winning_sentence = '%s'", last_seg_time, false])

					# Sorting active segs by vote count
					@sorted = @active_segs.sort { |a,b| b.sentence.get_vote_count <=> a.sentence.get_vote_count }
				end
			end

			next_winner_time = @win_seg.last.updated_at + update_timer_in_sec
			@display = next_winner_time.in_time_zone("Pacific Time (US & Canada)").strftime("%I %M %p") 

			@contributors = []
			@win_seg.each do |seg|
			@contributors << seg.sentence.user
		end
	end

	def new
		if user_signed_in?

			@root_url = "https://source.unsplash.com/"
			@story = Story.new
			@segment = Segment.new
			@sentence = Sentence.new
			# Need to ajax this to be a dynamic search
		else
			redirect_to '/users/sign_in'
		end
	end

	def edit
	end

	def create
		# puts Unsplash::Photo.find("tAKXap853rY").methods
		@story = Story.create(story_params)
		segment = Segment.create(story_id: @story.id, winning_sentence: true)
		@first_sentence = story_params[:sentence]
		sentence = Sentence.create(segment_id: segment.id, user_id: story_params[:user_id], sentence: @first_sentence)
		# vote = Vote.create(vote_count: 1, user_id: story_params[:user_id], sentence_id: sentence.id)
	 	respond_to do |format|
	    if @story.save
	      format.html { redirect_to @story, notice: 'Story was successfully created.' }
	      format.json { render :show, status: :created, location: @story }
	    else
	      format.html { render :new }
	      format.json { render json: @story.errors, status: :unprocessable_entity }
	    end
  	end
	end

	def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end		
	end
	
	def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to Storys_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
	end


	def images
		if request.xhr?
			search = params[:search]
			@photos = Unsplash::Photo.search("#{search}")

			ids = []
			@photos.each do |photo|
				ids << photo.id
			end
			
			# root_url "https://source.unsplash.com/"
			# query
			# hash = {}
			p @photos[0].methods
			#TODO build the html links here and send it back.
			render json: @photos
		else
			new_story_path
		end
	end

	def favorite
		if request.xhr?
			current_story = Story.find(params[:id])
			reponse = current_story.liked_by current_user
			reponse.to_s
		end
	end

	def unfavorite
		if request.xhr?
			puts params
			current_story = Story.find(params[:id])
			reponse = current_story.disliked_by current_user
			reponse.to_s
		end
	end

	private

		def story_params
			params.require(:story).permit(:title, :image_url, :user_id, :sentence)
		end

end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/index.erb
<div class="index-c">
	<div class="story_list_container">
		<% @stories.each do |story| %>
			<!-- one story box -->
			<div class="story_container">
				<%= link_to story_path(story), method: :get do %>
					<div class="image_container" style="background-image: url(<%="#{@root_url}#{story.image_url}#{@query}"%>)">
					<div class="title_container_index">
						<h1 id="show_titles_h1"><%= story.title %></h1>
					</div>
				</div>
				<div class="description_container">
					<div class="first_sentence_container">
					</div>
					<div class="notes_container">
						<div class="contribute_hearts">
							<p><%=story.get_likes.size%><span class="material-icons">favorite</span></p>
						</div>
							<p><%= story.get_last_seg.sentence.sentence %></p>
					</div>
				</div></a>
			</div>
			<% end %>
		<% end %>
	</div>
		<div class="paginate">
			<%= will_paginate @stories %>
		</div>
</div>

app/views/stories/new.erb
	<div class="story_body_container">
		<%= form_for @story, :html => {:class => "story_form"} do |f| %>
			<!-- one story box -->
			<div class="story_container">
				<div class="image_container" id="cat_images">
					<div class="title_container">
					<%= f.text_field :title, placeholder: "Enter Title", :autocomplete => 'off'%>
					</div>
					<div id="icon-div">
						<button class="material-icons" id="img_icon">add_a_photo</button>	
					</div>
					<%= f.hidden_field :image_url %>
					</div>
						<div class="description_container">
							<div class="first_sentence_container">
							<%= f.text_area :sentence, placeholder:"Write your first sentence here...", :autocomplete => 'off'%>
						</div>
					</div>
				</div>
			<button id="cancel">Cancel</button>
			<%= f.hidden_field :user_id, value:current_user.id %>
			<%= f.submit "Submit", :class => 'submits'%>
			</div>
		<% end %>
	</div>
	<div id="pop-up-container" class="hidden animated">
		<div>
			<h1>search image category</h2>
		</div>
		<form id="pop-up">
			<input type="text" name="search" id="pop-search" autocomplete="off">
		</form>
		<div id="image_pop_up_container">
			<ul id="image-list">
				
			</ul>
		</div>
	</div>

	

app/views/stories/show.erb
<div class="story_show_container">
	<div class="center_show_story">
		<div class="image_show_container" style="background-image: url(<%="#{@root_url}#{@story.image_url}#{@query}"%>)">
			<div class="show_story_title">
				<h1 id="show_titles_h1"><%= @story.title %></h1>
				<ul class="bxslider">
					<% @win_seg.each do |seg| %>
						<li><%= seg.sentence.sentence %></li>
					<% end %>
				</ul>
			</div>
			<div class="description_continatiner">
				<div class="description_left_show_container">
					<div class="description_left_blocks">
						<p>Update: <%= @display %></p>
						<!-- Trigger/Open The Modal -->
						<button id="myBtn" class="material-icons">local_library</button>
					</div>
				</div>
				<div class="description_right_show_container" id=favs>
					<% if @liked %>
						<button type="submit" class="material-icons favorite favorites" value="<%=@story.to_json%>">favorite</button>
					<% else  %>
						<button type="submit" class="material-icons unfavorite favorites" value="<%=@story.to_json%>">favorite</button>
					<% end %>
					<div>
						<!-- contributors and like button goes here -->
					</div>
				</div>
			</div>
		</div>
		<% if user_signed_in? %>
			<div>
				<%= form_for @new_segment do |f| %>
				<%= f.text_area :sen, :class => 'story_show_input', placeholder:"Write here...", :autocomplete => 'off'%> 
				<%= f.hidden_field :story_id, value:@story.id %>
				<%= f.submit "create", :id => 'story_show_submit', :class => 'material-icons' %>
				<% end %>
			</div>
		<% end %>
		<div>
			<% @sorted.each do |active_seg| %>
				<div class="story_segments">
						<div class="segment_left">
							<button type="submit" class="material-icons up" value="<%=active_seg.to_json%>">keyboard_arrow_up</button>
							<% votes = active_seg.sentence %>
							<p class="vote_counts" id="vote<%="#{active_seg.id}"%>"><%=votes.get_likes.size - votes.get_dislikes.size%></p>
							<button type="submit" class="material-icons down" value="<%=active_seg.to_json%>">keyboard_arrow_up</button>
						</div>
					<div class="story_segment_body">

						<div class="segment_right">
							<p><%= active_seg.sentence.sentence %></p>
						</div>
						
					</div>
				</div>
			<% end %>
			<div>
			</div>
		</div>
	</div>

<!-- The Modal -->
	<div id="myModal" class="modal animated">

	  <!-- Modal content -->
	  <div class="modal-content">
	    <div class="modal-header">
	      <span class="close">×</span>
	      <h2 class="model_title"><%=@story.title%></h2>
	    </div>
	    <div class="modal-body">
	    <% @win_seg.each do |seg| %>
	      <p><%=seg.sentence.sentence%></p>
	    <% end %>  
	    </div>
	    <div class="modal-footer">
	      <h3>Novelist</h3>
	    </div>
	  </div>

	</div>
</div>