config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'stories#index'

  resources :stories do 
  	get "images"
    post "favorite"
    post "unfavorite"
  end
 
  resources :segments do
  	post "up"
  	post "down"
  end
  resources :sentences
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Novelist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Quicksand','application.css' %>
     <%= stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons','application.css' %>
  </head>

  <body>
    <div class="navigation-container">
        <div class="nav-img">
          <%= link_to image_tag('novelist.png'), stories_path, id: "home"%>
        </div>
        <div class="nav-list">
        <ul>
          <% if user_signed_in? %>
            <li>
              <%= link_to "Log off", destroy_user_session_path, 'data-method' => :delete, id:"log-off" %>
            </li>
          <% else %>
            <li>
              <%= link_to "Log in", new_user_session_path, id:"user" %>
            </li>
          <% end %>
          <li id:"new-story">
            <%= link_to "New Story", new_story_path, method: :get %>
          </li>

        </ul>
        </div>
    </div>
  	<!-- devise flash notices -->
    <%= yield %>
    <div class="notices hidden">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
  </body>
  <footer>
    <div class="footer-container">
    <!-- footer content goes here -->
      <div class="foot_content">
        <% if user_signed_in? == false %>
          <%= link_to "Log in to contribute to a story", new_user_session_path, id:"user" %>
        <% end %>
      </div>
    </div>
  </footer>
</html>